### ISSUE TITLE
Merchant response windows on closed escalated tickets. 

### ISSUE THREAD

**Issue by sharpaypal** [sharpaypal/financial-services-support#39]
## Task For Matt 

**Give a TLDR of what the task is.**

When an escalated ticket is solved, there is a short window in which a merchant's response will re-open the same ticket thread. If a merchant replies back after this window, they'll get the automated email telling the merchant they will need to reach out to support through support router. Full breakdown:

![image](https://screenshot.click/23-55-1j1v1-6dp6s.jpg)

We want to determine if the window currently set for our team is too short and is causing unnecessary friction for the merchant to contact support, about the same issue that was already escalated. 

**How long will the task take to complete? Is there a known due date?**

n/a

**What are the steps that will need to be taken, to complete this?**
Is there anyone or any team that should be involved/notfied?

* We need to confirm the length of time a ticket can be re-opened with a merchant response, but they get the automated email to contact support. 
* Review and determine if the length of time is sufficient for **majority** of cases that our team handles. 
* Learn if we can set custom response windows, per ticket type or form. _Ex - could the response window be longer for 1099k tickets, versus billing tickets?)_

**Anything else to include?** 

Laine was taking a look into this with support ops, to find out some initial information. Will follow up with them to see if we've heard back.  

@sharpaypal

**Comment by fastlaine** [comment]
We just need to send support ops the info and she said it's very simple and quick for her team to implement once we know what we want. They apply the exceptions by tags so we need to determine which tags we want to extend the window for as well as for how long.

Conversation with support ops: https://shopify.slack.com/archives/C0349J9PK/p1568669091323000

Here's my example ticket where I noticed this: https://shopify.zendesk.com/agent/tickets/13998030
The merchant had to follow up by phone here: https://shopify.zendesk.com/agent/tickets/14100243

We will see this often with 1099 tickets and we often don't hear back for 6 months or more. These are merchants we've been trying to get updated tax details from and any friction we add at all will mean we probably won't get a response. I would argue that at least for 1099 tickets, the window should be set at something huge like 1 year (open to discussion).

**Comment by Melissa-Johnston** [comment]
I have a great example here! I was liaising with the account owner of a store back in June. They had just asked to update an address, but I noticed they also submitted tax details for an LLC. I asked for clarification from them on whether they also wanted those details updated. But they never responded and the ticket ended up closed. They finally responded last week (Sept 19th), so 3 months later, and it was redirected to the general support queue where they were given incorrect information and the ticket was again solved out.
My original ticket: https://shopify.zendesk.com/agent/tickets/13216094
Follow up ticket: https://shopify.zendesk.com/agent/tickets/14294116

**Comment by righlach** [comment]
My original ticket: https://shopify.zendesk.com/agent/tickets/14164407

In the follow-up chat ([ticket](https://shopify.zendesk.com/agent/tickets/14278781)), Tami says specifically:

```I did reply back to his e-mail and was told that I could not generate a ticket through e-mail.```

That said, Tami then managed to reply back to the email successfully in the original ticket, causing not only merchant frustration but also confusion since there are now two escalations.

**Comment by sharpaypal** [comment]
Screenshot of Laine's convo with support ops before link goes dead:

![image](https://screenshot.click/22-08-via45-gobw9.jpg)

**Comment by sharpaypal** [comment]
Thanks for digging into that with support ops Laine, and everyone else for the examples! This seems specific to 1099ks, and I wasn't finding similar pain-points with general billing or payments tickets. _Since when we reach out to Stripe or waiting to hear back, the team tends to set tickets to "pending" or "on-hold"._

1099k seems to be a bit unique, so I feel this is up to the tasks force's discretion of what to set that window as. Feel free to reach back out to Ops, and have it set as you see fit for 1099k escalations. 

Going to close this, but feel free to re-open if you think I missed something. Cheers!
