### ISSUE TITLE
LTS and transferring credit

### ISSUE THREAD

**Issue by piaMarisa** [sharpaypal/financial-services-support#41]
#### Give a TLDR of what you're trying to solve.

Currently, if a merchant on an annual billing cycle closes their store during that cycle, should they reactivate while still in said cycle their annual plan will resume. The potential problem being that if they close their store and request the remainder of their subscription payment balance be transferred over to another of account; they can still reactivate their closed account afterwards and resume their plan as nothing would prevent them from doing so. 

#### Do you have an idea on what the process should be? If so, please share. 

Suggested ideas so far (use tools we already have at our disposal):

- When a merchant requests the remainder of their balance on annual plan be transferred to another account, lock the Admin after the store is closed to prevent it being opened again.
- Downgrade to a monthly plan first before merchant closes their store. (provided store is still open) 
- Put shop on trial subscription (without creating an invoice) and then cancel it again (so that the last active subscription isn't the long term subscription anymore)

Longterm:

- Ideally some other means whereby the onus isn't on the merchant to cancel their store again but also allows them to reactivate their account again and select a new plan (which locking their Admin would not allow for). 
-Perhaps something in the internal that we could check off that would trigger resetting the merchant's billing cycle to 0 and force them to pick a plan again in the instance where we transfer over balances from annual plans to another account.

#### Why is this important to address? 

1. To prevent merchants being able to have two accounts open for the price of one. 
2. To ensure merchants don't accidentally reactivate an account unknowingly and not realise they have another account open till they are billed again for their annual plan on a store they thought they closed.

#### What team(s) does this affect? Who are the possible stakeholders?

- FSS, Billing, Natalie Bettenburg

#### Please include any relevant Githubs, GuruCards, tickets, examples etc. 

Slack conversation with billing-devs:
- https://shopify.slack.com/archives/C034BB8QA/p1569265603216500

Github:
- https://github.com/Shopify/finance-ops/issues/1762

Guru cards:
- https://app.getguru.com/card/iEBogRGT/Refactoring-LongTerm-Subscriptions-

Reactivation scenario breakdown: 
- https://docs.google.com/document/d/1B0V7zJ14TPcLMEPIcK32eNqL4OE-brGl9j0rp6pLlOg/edit

Care Package: 
- https://docs.google.com/document/d/1ZwRZUwF7s4V51UoG2NRGH2Tp3bIifX04hwc1K5LIOfQ/edit

Ticket example:
- https://shopify.zendesk.com/agent/tickets/13815401

@anyacasey @deborahisaac @sharpaypal

**Comment by anyacasey** [comment]
We can discuss more next week, but I feel that the third suggestion above of placing the cancelled account on trial and then re-cancelling would be the best approach for these scenarios at the moment. 

Example here: https://app.shopify.com/services/internal/shops/6345985

**Comment by anyacasey** [comment]
**Update October 21st**

* Playbooks updated
* Team Trello almost ready to ship

**Comment by deborahisaac** [comment]
Steve raised a good question in the BC channel that we'll want to look into as well: 

> That makes me wonder what the deal is if someone cancels on annual, gets a refund, and then reactivates. Do they get their year for free?

We do quite a lot of annual refunds; do we want to add the trial step to the process? Though I don't have any stats on this, my feeling is that there aren't a lot of merchants that would reactivate in this circumstance. In https://github.com/Shopify/finance-ops/issues/1762, I asked about the possibility of adding a button so that we could delete the merchant's last active subscription.

**Comment by anyacasey** [comment]
**Update shipped:** Trello card with related Playbook updates can be accessed [here] (https://trello.com/c/SBsDE57w)
