### ISSUE TITLE
Incident (October 9): Taxes not charged/applied for orders with a USA shipping address

### ISSUE THREAD

**Issue by deborahisaac** [sharpaypal/financial-services-support#57]
## Product Launch or Change 

**Give a TLDR of what the launch or change is.**
Incident: https://github.com/Shopify/incident-response/issues/418

**Did you check the team Trello board to see if it's already being worked on? Yes or No**
It's not being worked on yet.

**Link relevant project resources**
- https://github.com/Shopify/incident-response/issues/418
- Slack channel: #ir-oct19-usataxes

**From what you know, what tasks do we need to complete to be ready?**

IR reached out re: the best way to compensate merchants. I suggested doing a balance adjustment for Shopify Payments merchants and a subscription credit for those merchants not using Shopify Payments. I helped them identify what would be needed in terms of data. We are currently waiting for Finance to approve (~$70,000 USD) and then we may have to provide further input re: the maintenance tasks.

**What is the estimated launch date?**

Unsure.

@anyacasey @deborahisaac @sharpaypal

**Comment by sharpaypal** [comment]
Great summary! Looks like finance [just provided approval](https://github.com/Shopify/financial-disruptions/issues/88) for the comp. Expect IR to reach back out soon.

**Comment by joshlutz5** [comment]
Fyi I've looped in [SP devs](https://shopify.slack.com/archives/C7QM4DDV4/p1571749563461900) and [billing devs](https://shopify.slack.com/archives/C034BB8QA/p1571749310199100).

**Comment by deborahisaac** [comment]
@joshlutz5 Thanks for the heads up! Closing as no further action is required on our end. Funds have been returned to merchants and comms went out October 24. Posted in billingsp-updates to notify the team.
